### ISSUE TITLE
Upgrade from pywb 0.11.1 to 0.30.1 breaks some legacy video recordings

### ISSUE THREAD

**Issue by despens** [webrecorder/webrecorder#104]
Example: http://webenact.rhizome.org/vvork/20141006184357/http://www.vvork.com/?m=201212

The bottom of the page contained a vimeo embed with a replaced HTML default player, which does not work anymore.

**Comment by ikreymer** [comment]
This should really be in pywb not Webrecorder, to avoid confusion, and so I can better keep track :)
