### ISSUE TITLE
Recording Tweets crashes webrecorder.

### ISSUE THREAD

**Issue by k0nsl** [webrecorder/webrecorder#110]
This is a preliminary 'report' with no details as I have not investigated it.

The issue: if I record a tweet it crashes webrecorder and I have to start it up again. Could this be a memory issue?
I have 3.77 GB total memory. Runs Debian 8 with kernel 3.16.0-4-amd64.

```
         _,met$$$$$gg.           root@S1NE23
      ,g$$$$$$$$$$$$$$$P.        OS: Debian 8.4 jessie
    ,g$$P""       """Y$$.".      Kernel: x86_64 Linux 3.16.0-4-amd64
   ,$$P'              `$$$.      Uptime: 90d 14h 46m
  ',$$P       ,ggs.     `$$b:    Packages: 806
  `d$$'     ,$P"'   .    $$$     Shell: bash 4.3.30
   $$P      d$'     ,    $$P     CPU: Intel Core2 Quad CPU Q6600 @ 2.403GHz
   $$:      $$.   -    ,d$$'     RAM: 1135MB / 3954MB
   $$\;      Y$b._   _,d$P'
   Y$$.    `.`"Y$$$$P"'
   `$$b      "-.__
    `Y$$
     `Y$$.
       `$$b.
         `Y$$b.
            `"Y$b._
                `""""
```

I will investigate further and update as I find out more.

**Comment by ikreymer** [comment]
Hmm.. this does not happen on the hosted version.. Can you provide more info from the docker containers? `docker-compose logs` should print the output from all of them.. hopefully there is a stack trace or other error information that could be helpful.
