### ISSUE TITLE
Followed Page Anchors not reflected in visible URLs

### ISSUE THREAD

**Issue by despens** [webrecorder/webrecorder#13]
If a web capture contains links with page anchors, following such a link within a page doesn't add the page anchor to the browser's URL bar nor webrecorder's URL bar.

**Comment by ikreymer** [comment]
@despens, I think this may now be fixed (19ac27ffe4d2ac59f007b9b743dc7ee07c9a268a) can you double check?

**Comment by m4rk3r** [comment]
confirmed fixed
