### ISSUE TITLE
Re-written cookies accumulate in browser, causing errors and potential security risks

### ISSUE THREAD

**Issue by despens** [webrecorder/webrecorder#142]
All cookies of web-sites that are being recorded are currently re-written to the domain webrecorder.io. The cookie jars in client browsers are filling up until further usage of webrecorder becomes nearly impossible. Users clearing their cookie jars typically helps, or running the recording browser in "private" mode.

Storing the cookies server-side (#79) might be one way to do it, other possibilities include a front-end to manage cookies, or using on-demand sub-domains.

**Comment by ikreymer** [comment]
This has been much improved in the upcoming version, as cookies are stored at the exact path. Server-side handling in #79 is used to augment the exact path when accessing cross-domain requests.

I believe the currently deployed version has them apply to the root domain, which is problematic.

**Comment by ikreymer** [comment]
In the new version, all cookies are set to the rewritten path, never on the root domain. With temp sessions, each temp session will have its own set of cookies. The server-side temp cookie store handles the domain mapping for cookies. Closing this, unless issues arise in the new version.
Will open other issues for separate security concerns.
