### ISSUE TITLE
Make collection and recording ids renamable.

### ISSUE THREAD

**Issue by ikreymer** [webrecorder/webrecorder#143]
Backend: restructure to use flat hierarchy to avoid having to move files when collection or recording id names change.

Frontend: Just need to add editing capability in the UI.

**Comment by ikreymer** [comment]
JSON API will be: 
`/api/v1/recordings/<rec>/rename/<new_rec>` and /api/v1/collections/<coll>/rename/<new_coll>`

**Comment by mashalifshin** [comment]
on collection page, abilitiy to edit title
on collection page, ability to edit the url

**Comment by mashalifshin** [comment]
- allow collection title renaming
- allow collection url renaming
- allow recording title renaming and the url changes automatically
