### ISSUE TITLE
Confusion about different modes

### ISSUE THREAD

**Issue by despens** [webrecorder/webrecorder#16]
Users have been reporting confusion about what the "recording" mode does.
Erroneously creating multiple recordings of the same resource has been a very common problem. Current usage patterns indicate that users want to make one complete recording of a web resource, recording the same resource at different points in time seems like a less-frequently used feature.

**Proposed solution:**

The four main functions of Webrecorder shall be reduced to only three:

old function | new function
---------------|-----------------
Recording | :skull:
Patching | Record
Pass through | Preview
Replay | Replay

![selection_089](https://cloud.githubusercontent.com/assets/571494/10287042/ebd0741e-6b5e-11e5-93e5-a53ba247cb88.png)

The default recording mode shall be the same as patching used to be before.

To further avoid multiple recordings, Webrecorder shall always start up in "Preview" mode, so that users all the time see what they record before making the first recording.

To start a new "time layer" for a recording, another interface element will be required.

**Comment by ikreymer** [comment]
The next release will have just a record and replay mode!

**Comment by mashalifshin** [comment]
This issue is obsolete now because the new workflows do not have a mode dropdown.
