### ISSUE TITLE
User confusion about main dropdown menu

### ISSUE THREAD

**Issue by despens** [webrecorder/webrecorder#17]
Users have been reporting confusion about the role of the dropdown menu for selecting webrecorder's mode of operation: they are mistaking it for a button and are creating unwanted multiple recordings of the same resource. Especially the reload-action of the browser is perceived as a surprise when operating the menu.

**Proposed solution:**

The dropdown menu is moved to the right edge of the URL bar and is visually detached from it. A separate "Go" button, also visually detached, will make the action of switching between different modes more intentional.

![selection_090](https://cloud.githubusercontent.com/assets/571494/10287389/b3369258-6b60-11e5-9b40-0ad63c649868.png)

Probably, the background colors' saturation of the dropdown menu have to be toned down to make them less confusable with a button.

**Comment by ikreymer** [comment]
Removing the drop down menu in the next release!

**Comment by ikreymer** [comment]
Keeping open until the next release!

**Comment by mashalifshin** [comment]
This issue is obsolete now because the new workflows do not have a modes.
