### ISSUE TITLE
Indicator for space running out or user session ending during recording missing

### ISSUE THREAD

**Issue by despens** [webrecorder/webrecorder#189]
There seem to be two cases where recording fails due to "outside forces": the user has no more space left, or is being logged out of Webrecorder for some reason.

The recording page should indicate with a flash message if either happens.

**Comment by ikreymer** [comment]
- There's already warning flash message in place that will show when about to run of space, and then when space has actually run out.

- Raised the 'idle time' to auto-logout to 30 mins (was 2 mins) before, otherwise it should not automatically log out.. If happens, should open another issue.
