### ISSUE TITLE
Figure out better embed url for embedded replay view

### ISSUE THREAD

**Issue by ikreymer** [webrecorder/webrecorder#207]
Currently, the embed url is used at: https://rhizome.org/editorial/2015/aug/6/why-museum-collect-vines/ and is of the form: `https://beta.webrecorder.io/Rhizome/footyvinesnfm/embed/https://vine.co/v/erMptAn7tIw/embed/simple`

Unfortunately, this conflicts with the new recording scheme, so we need to decide on a better embed url, and something more customizable.. 

Perhaps we put it in the beginning with `_embed`

`https://webrecorder.io/_embed/Rhizome/footyvinesnfm/https://vine.co/v/erMptAn7tIw/embed/simple`

We'll likely want to support various options later, eg. `_embed:XYZ` or something. Needed for the release and also need to fix the article (or add a redirect)

Any thoughts on this @despens

**Comment by harlantwood** [comment]
I like:

> beginning with _embed
