### ISSUE TITLE
Proper way to proxy?

### ISSUE THREAD

**Issue by lenisko** [webrecorder/webrecorder#208]
Is there any proper way to run this thing behind proxy?
I mean I want to use it at production, but there are some problems: __Recording__, __Preview__ are not working. 
After investigation, in console I was getting alerts about mixed content like `http://localhost:8089/static/__pywb/wb.js` etc. 

Host nginx site config:
```
server {
    listen 80;
    server_name example.com;
    return 302 https://$server_name$request_uri;
}

server {
    listen 443 ssl;
    server_name example.com;

    ssl_certificate /etc/letsencrypt/live/example.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/example.com/privkey.pem;

    location / {
        proxy_set_header X-Real-IP $remote_addr;
        proxy_pass http://localhost:8089;
    }
}
```

**Comment by ikreymer** [comment]
Yes, definitely possible to proxy. We use this with our deployment. You just need to include the scheme with the `proxy_set_header X-Forwarded-Proto $scheme` which the webrecorder nginx checks.

Here's our current config:

```
        location / {
           proxy_pass http://localhost:8089;
           proxy_set_header Host $host;
           proxy_set_header X-Forwarded-Proto $scheme;
           proxy_set_header X-Real-IP $remote_addr;
           proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }
```
