### ISSUE TITLE
Ability to disable recording for anonymous users

### ISSUE THREAD

**Issue by lenisko** [webrecorder/webrecorder#213]
Hello!

It would be really nice to have ability to disable recording for non-registered users from configuration file.

**Comment by kzahel** [comment]
I'd like this very much too!

**Comment by kzahel** [comment]
The interface could be tweaked here
https://github.com/webrecorder/webrecorder/blob/master/webrecorder/webrecorder/templates/homepage_recorder.html
to at least not show the option to record. Not sure about the logic to actually properly prevent recordings being made.

**Comment by m4rk3r** [comment]
We'll add this to our near-term todos, thanks!

**Comment by ikreymer** [comment]
@kzahel @lenisko Just added `ANON_DISABLED=1` to your `wr.env` file and temporary/anonymous recording should be disabled.

**Comment by kzahel** [comment]
This is freaking great! I should have time to test it out soon(ish) and will update you and let you know how it works
Looking forward, this is going to be a real benefit to our program! Thank you!
