### ISSUE TITLE
Administration script

### ISSUE THREAD

**Issue by lenisko** [webrecorder/webrecorder#214]
Just an idea, but I think ability to manually adding users from console would help with script usage.

Right now lets say I want to use this script on my own so I have to create new account which require me to:
* Send an e-mail (by default ports are blocked on many servers) also sending itself is lets say complicated on default settings, many mail providers are blocking not verified mails (unless I'm doing something wrong) like Google - e-mail is not even in Spam/Trash
* Configure remote SMTP server

Simple script like add_user.py with ability to add users would be sufficient.

**Comment by ikreymer** [comment]
yes, this is a really good idea and something we've been thinking about. thanks for making this issue. email in particular has been problematic, as you point out, Google blocks the default SMTP server because its not verified.

Will update this issue with any progress made.

**Comment by m4rk3r** [comment]
@lenisko we’ve added a new `admin.py` script to help with low level management of users.

For full details check `python admin.py --help` but for adding new users you can either pass the info as arguments e.g. `python admin.py -c user@example.com newuser Password! archivist 'full name'` or enter info interactively by running `python admin.py -c` without any arguments. Hope this helps!

**Comment by lenisko** [comment]
Sorry that I didn't leaved any feedback before but I was away.
Great job guys!
