### ISSUE TITLE
Problem with Temp Dir?

### ISSUE THREAD

**Issue by kzahel** [webrecorder/webrecorder#223]
I installed on a fresh ubuntu 16.04 server image, with all default configs. The website loads up looking great on port 8089 but I always see 0 bytes recorded in the UI, and running without -d I see an error writing to the temporary directory.

I am new to docker, so I am not sure how to get a shell and check the folder. I tried docker ls and docker attach but that didn't seem to do what I want. :-\

app_1             | 2016-08-20 17:58:40,968: [INFO]: Starting new HTTP connection (1): recorder
webagg_1          | /usr/local/lib/python3.5/site-packages/urllib3/connectionpool.py:838: InsecureRequestWarning: Unverified HTTPS request
 is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/security.html
webagg_1          |   InsecureRequestWarning)
webagg_1          | [pid: 15|app: 0|req: 13/59] 172.18.0.7 () {32 vars in 1298 bytes} [Sat Aug 20 17:58:40 2016] POST /live/resource/postr
eq?param.user=temp-PLZBE3I7&param.coll=temp&param.rec=recording-session-5&closest=now&url=https%3A%2F%2Fpixel.facebook.com%2Fsi%2Fkappa%2F
async%2F%3FKa%3DAbEy68WjXipDa1w2%26Kt%3D1471715920850%26Ko%3Da%26__a%3D1%26__be%3D-1%26__dyn%3D7xeXxaER2HwNJ0ZwRAKGzEyay6-C11xG3Kq2i5U4e1o
x27QdwPwDyUG4XzEa8uwh9Vobo88lwIwHwJwpUO6Egx61YCBxZ3E%26__pc%3DPHASED%253ADEFAULT%26__req%3D7%26__rev%3D2518278%26__user%3D0%26asyncSignal%
3D1607%26lsd%3DAVr0diR9 => generated 2711 bytes in 31 msecs (HTTP/1.1 200) 6 headers in 489 bytes (13 switches on core 399)
app_1             | 2016-08-20 17:58:41,008: [DEBUG]: "POST /record/live/resource/postreq?param.user=temp-PLZBE3I7&param.coll=temp&param.r
ec=recording-session-5&closest=now&url=https%3A%2F%2Fpixel.facebook.com%2Fsi%2Fkappa%2Fasync%2F%3FKa%3DAbEy68WjXipDa1w2%26Kt%3D14717159208
50%26Ko%3Da%26__a%3D1%26__be%3D-1%26__dyn%3D7xeXxaER2HwNJ0ZwRAKGzEyay6-C11xG3Kq2i5U4e1ox27QdwPwDyUG4XzEa8uwh9Vobo88lwIwHwJwpUO6Egx61YCBxZ3
E%26__pc%3DPHASED%253ADEFAULT%26__req%3D7%26__rev%3D2518278%26__user%3D0%26asyncSignal%3D1607%26lsd%3DAVr0diR9 HTTP/1.1" 200 None
recorder_1        | Traceback (most recent call last):
recorder_1        |   File "/webrecore/recorder/recorderapp.py", line 48, in _write_loop
recorder_1        |     self._write_one()
recorder_1        |   File "/webrecore/recorder/recorderapp.py", line 65, in _write_one
recorder_1        |     self.writer.write_req_resp(req, resp, params)
recorder_1        |   File "/webrecore/recorder/warcwriter.py", line 112, in write_req_resp
recorder_1        |     self._do_write_req_resp(req, resp, params)
recorder_1        |   File "/webrecore/recorder/warcwriter.py", line 427, in _do_write_req_resp
recorder_1        |     return self._write_to_file(params, write_callback)
recorder_1        |   File "/webrecore/recorder/warcwriter.py", line 453, in _write_to_file
recorder_1        |     out = self._open_file(filename, params)
recorder_1        |   File "/webrecore/recorder/warcwriter.py", line 371, in _open_file
recorder_1        |     fh = open(filename, 'a+b')
recorder_1        | FileNotFoundError: [Errno 2] No such file or directory: '/data/warcs/temp-PLZBE3I7/rec-20160820175841016175-4097da1c0d
50-ZXGJZEJH.warc.gz'

**Comment by ikreymer** [comment]
I think this was a permissions issue with `./data` dir, where the Docker container did not have access to write to the data dir. I think I improved this recently by not running Docker as root but as a new user and mapping it to the user with uid 1000. This isn't guaranteed to work in all cases, but should at least make this less likely. If this happens again, the `./data/warcs` dir can be set to be world writable. Let me know if this happens again on a new deployment
