### ISSUE TITLE
Downloaded archives max out at 1gb

### ISSUE THREAD

**Issue by michaelconnor** [webrecorder/webrecorder#266]
Dragan instructed me to download both of the (one) (two) collections before combining them. The downloaded files, however, always stop at around 1.0 GB. When I re-upload them they are incomplete (incomplete re-upload one) (incomplete re-upload two).

**Comment by michaelconnor** [comment]
These collections: https://webrecorder.io/dillon/ppw-the-beast-1 https://webrecorder.io/dillon/ppw2

**Comment by michaelconnor** [comment]
These re-uploads https://webrecorder.io/dillon/ppw-the-beast-1-2
https://webrecorder.io/dillon/ppw2-2

**Comment by ikreymer** [comment]
I can confirm that this is repro-ing locally, but not on another AWS machine. Possibly a timeout issue?

**Comment by michaelconnor** [comment]
This is the most urgent of the Puppies Puppies problems - the archive is unusable by the researcher as is, because the two archives can't combined, because they're truncated.

**Comment by ikreymer** [comment]
I think this should work now after increasing read timeout and ensuring no buffering. Downloaded the first 2.7GB+ file in full locally. @michaelconnor can you double check as well?

**Comment by ikreymer** [comment]
Confirmed that downloading should be working now, though uploads of this size currently reach a timeout (another fix coming).

However, if the intent is to combine two collections, this can be accomplished simply by moving recordings together into same collection there should be no need to download and re-upload for that use case. Or is there something that's needed @michaelconnor @despens ?

**Comment by michaelconnor** [comment]
(The issue was that downloading was necessary before merging as the
collection represented dozens of hours of labor and needed to be backed up
before attempting merge)

**Comment by ikreymer** [comment]
Something to keep in mind, the merge two collections is just changing metadata about what recordings are in which collection, and we don't yet have a recording-level merge (nor is it needed here). Merging collections in this sense doesn't move any data internally, so is actually less error prone than downloading many GB of data and re-uploading :)
