### ISSUE TITLE
Broken links in insta archive 

### ISSUE THREAD

**Issue by michaelconnor** [webrecorder/webrecorder#267]
There are broken links that I can not figure out how to fix. The playback of certain videos is cut off in both the patch tool and the replay tool, and some images will not load (they are not deleted—this prompts a different page). 

https://webrecorder.io/dillon/ppw2/https://www.instagram.com/p/BK8sBn9gnmQ/ -- Rerecorded (patch-6)

https://webrecorder.io/dillon/ppw2/https://www.instagram.com/p/BJMVE1DgG-Y/ -- Rerecorded (patch-6)

https://webrecorder.io/dillon/ppw2/https://www.instagram.com/p/BIqgcKTATQV/ -- Rerecorded (patch-6)

https://webrecorder.io/dillon/ppw2/https://www.instagram.com/p/BGAJ3osGmqL/ -- Rerecorded (patch-6)

https://webrecorder.io/dillon/ppw2/https://www.instagram.com/p/BFZQc8smmnh/ -- Rerecorded (patch-6)

https://webrecorder.io/dillon/ppw2/https://www.instagram.com/p/BEmyqQdmmuh/?taken-by=puppiespuppieswoof -- Original Page 404

https://webrecorder.io/dillon/ppw2/https://www.instagram.com/p/BEOv8lKGmmr/?taken-by=puppiespuppieswoof -- Original Page 404

https://webrecorder.io/dillon/ppw2/https://www.instagram.com/p/BC8ciBeGmna/ -- Rerecorded (patch-6)

https://webrecorder.io/dillon/ppw2/https://www.instagram.com/p/BCbm3X2mmlU/ -- Rerecorded (patch-6)

https://webrecorder.io/dillon/ppw2/https://www.instagram.com/p/BBx0QrAmmsE/?taken-by=puppiespuppieswoof  -- Original Page 404

**Comment by michaelconnor** [comment]
https://webrecorder.io/dillon/ppw2/https://www.instagram.com/p/BAvBbDSmmuw/?taken-by=puppiespuppieswoof
https://webrecorder.io/dillon/ppw2/https://www.instagram.com/p/uJvuElmmp4/

https://webrecorder.io/dillon/ppw2/https://www.instagram.com/p/ttGppNGmg3/

https://webrecorder.io/dillon/ppw2/https://www.instagram.com/p/ruf9Q_Gmjq/

https://webrecorder.io/dillon/ppw2/https://www.instagram.com/p/pRzEg2GmlM/
https://webrecorder.io/dillon/ppw2/https://www.instagram.com/p/_ktKXoGmgI/

https://webrecorder.io/dillon/ppw2/https://www.instagram.com/p/7bfc9Ummjb/

**Comment by michaelconnor** [comment]
https://webrecorder.io/dillon/ppw2/https://www.instagram.com/p/47a7ADGmk_/

https://webrecorder.io/dillon/ppw2/https://www.instagram.com/p/1YM_AGmqA/

https://webrecorder.io/dillon/ppw2/https://www.instagram.com/p/1LmFiVGmjk/

https://webrecorder.io/dillon/ppw2/https://www.instagram.com/p/xuQ-pYGmgS/

**Comment by ikreymer** [comment]
It seems like there's several types of issues:

- Truncated videos -- Will need to take a look at this more, patching won't fix it currently because the resource is there, just truncated..

- Recorded pages that have certain errors (5xx) -- Will need to update patching to support re-recording errors. It seems most of the ones where the images are missing fall into this category.

- Pages that are just gone -- Nothing we can do here.

I think that covers all of the errors.. anything else that you've seen?

**Comment by michaelconnor** [comment]
Can you clarify the third point? What's an example of a resource that's
just gone? Can it be patched? Thx!

**Comment by ikreymer** [comment]
I've updated the above list with the three that appear to be 404 on instagram.
Probably easiest to add comments in the list above (or move to spreadsheet).

For the truncated videos and 504 errors, probably best to just re-record the video or the missing image. This can be done just by starting a 'New Recording' and entering the urls directly.

**Comment by ikreymer** [comment]
The urls have been rerecorded and are under two recordings: patch-6 and patch-7
Things that are missing have been noted. Of course, we need to fix the large bookmark display, but that's a separate issue.
