### ISSUE TITLE
Communicating pending size along with total size

### ISSUE THREAD

**Issue by ikreymer** [webrecorder/webrecorder#287]
With #259, there is now tracking of pending in flight responses, and that is included in the total size shown to the user. However, when downloading the WARC, this data can not yet be included as it hasn't finished downloading. The size for the downloaded WARC must therefore only include the finished data. But doing so will result in WARC sizes that may be smaller then what is shown.

This raises a UI issue of how the pending size should be communicated to the user.
Perhaps the pending size should be listed separately? Or there could be an indicator that there are still 'in-flight' responses? Should it be shown differently when downloading then the recording bar size counter?

**Comment by ikreymer** [comment]
After latest change, recording size counter includes the pending size (due to WS update) but replay and collection info page does not.

**Comment by m4rk3r** [comment]
👍 Upcoming release will include displaying `pending_size` as flashing record indicator hard drive style.
