### ISSUE TITLE
Create browser addon for detecting leaking requests

### ISSUE THREAD

**Issue by despens** [webrecorder/webrecorder#29]
Webrecorder cannot reliably detect leaking http requests, this can only happen within the recording browser.

Probably an addon for Firefox and Chrome could at least find and point out leaks, offering options to report the issue, or offer to record these leaking resources manually (in case the leaking is fixed in the future.)

**Comment by ikreymer** [comment]
I'd like to avoid browser plugins for now -- if we do that, might as well support recording through it..
It is actually possible to detect leaks w/o a plugin also, maybe a bit intrusive (eg. get the HTML, search for any unrewritten urls in tags and/or css). Also, could have an automation mode that loads replay with a proxy and detects leaks that way, so several options..

Do you have specific examples of leaks? ;) Most should be eliminated, except when dealing with Flash..

**Comment by despens** [comment]
I see.
Don't have specific examples of leaks, but am paranoid that I am missing some ;)
I don't necessarily think of the browser addon as a part of webrecorder packge, more as a quality checking/debugging tool that is used internally.

**Comment by edsu** [comment]
It would be neat to have a button to press that would double check for leaks. I have no idea how such a button would work, but in principle it seems like a pretty useful thing to have because otherwise you have to drop into dev tools and watch network connections.

**Comment by ikreymer** [comment]
One way would be to grab the `document.documentElement.outerHTML` of the replay, parse and analyze for any standard attributes or css leaks.. This will not catch everything though, but may catch significant leaks (such as images), which would indicate some other issue.. (probably JS related). Flash would also not be caught with this, but could detect the presence of Flash.

A more thorough approach would be to launch the page in a container (a la Netcapsule), in replay mode, but with a proxy server that simply detects any request not made to webrecorder.io, and flags that as a leak.. This could be either user driven or automated, and will definitely catch Flash leaks and can further analyze the page content..

**Comment by despens** [comment]
Ideas will be useful in a more general and symmetrical QA service, not a browser addon. Closing.
