### ISSUE TITLE
Create new collection added to top of collection list in dropdown onlanding page?

### ISSUE THREAD

**Issue by michaelconnor** [webrecorder/webrecorder#294]
![screen shot 2017-01-23 at 11 50 43 am](https://cloud.githubusercontent.com/assets/4692677/22213426/34717306-e162-11e6-90cf-505457d63368.png)
It'd be nice if the drop-down menu let me add a new collection right from the landing page, not just choosing an existing one

**Comment by michaelconnor** [comment]
Just realized 'new collection' is there - it's just a bit buried in my 68 collections ha

**Comment by m4rk3r** [comment]
closed by ecc32bce15518691803af00339bd441e60086c8f
