### ISSUE TITLE
Download Collection from webrecorder.io fails

### ISSUE THREAD

**Issue by ppival** [webrecorder/webrecorder#295]
Possibly related to issue #20, but today while attempting to download a 252MB collection from webrecorder.io the download has failed thrice. This is my first time using the tool, so I don't know if this is a particularly large file or not. Using FF 50.1.0 on Win7, FWIW

**Comment by ikreymer** [comment]
Hi, thanks for reporting the issue. We have not seen this recently, the logs report that the entire file was served.. Was any error message displayed when it failed, or just the browser stopped downloading?

**Comment by ppival** [comment]
Sadly, FF simply says Failed - webrecorder.io  I did finally get it all
down via Chrome!

--
Paul R. Pival
http://distlib.blogs.com

**Comment by edsu** [comment]
FWIW, I was just able to download a 103 MB collection using Firefox 50.1.0

**Comment by ikreymer** [comment]
I just downloaded a 374MB collection in FF 50 and in Chrome, over a relatively slow connection.. I think will chalk this up to networking errors, but will reopen if I find anything specific.
