### ISSUE TITLE
ERROR? : for nginx  Cannot start service nginx

### ISSUE THREAD

**Issue by eAkti** [webrecorder/webrecorder#307]
Dockerfile is modified accordin to ubuntu:16.04.

I run locally; docker-compose up -d it ends with the following message:

sudo docker-compose up -d
Starting webrecorder_data_1
webrecorder_mailserver_1 is up-to-date
Starting webrecorder_redis_1
Starting webrecorder_proxy_1
Starting webrecorder_shepherd_1
Starting webrecorder_webagg_1
Starting webrecorder_recorder_1
Starting webrecorder_app_1
Starting webrecorder_nginx_1

ERROR: for nginx  Cannot start service nginx: oci runtime error: container_linux.go:247: starting container process caused "exec: \"nginx\": executable file not found in $PATH"
ERROR: Encountered errors while bringing up the project.

**Comment by ikreymer** [comment]
Were you able to get it to work? We've never seen this issue.
