### ISSUE TITLE
"Streamed" warc isn't indexed by pywb

### ISSUE THREAD

**Issue by despens** [webrecorder/webrecorder#31]
Upon adding a streamed warc file to a collection, wb-manager says:
```
Error: int() argument must be a string or a number, not 'NoneType'
```
The indexing process is stopped.

Using pywb 0.10.9

**Comment by ikreymer** [comment]
By streamed, do you mean the all collection download? Can you send it to me?

**Comment by despens** [comment]
Yes, the all collection download. File is on the way.

**Comment by ikreymer** [comment]
Was caused by not-fully downloaded file.. Should add a way to verify download #19

**Comment by ikreymer** [comment]
I have seen this also.. I think there is some issue that causes the All Collection WARC to get truncated occasionally..
