### ISSUE TITLE
New collection doesn't create a new collection

### ISSUE THREAD

**Issue by michaelconnor** [webrecorder/webrecorder#313]
When you select new collection from front page it just adds to an existing collection called 'new collection'

**Comment by ikreymer** [comment]
The "New Collection" is the name of the collection.. there's supposed to be a "+ Create New Collection" that hasn't been appearing, will fix this.

**Comment by ikreymer** [comment]
Fixed, you should now see a ` + Create New Collection` as first thing in the menu.
