### ISSUE TITLE
Uploading HAR Support

### ISSUE THREAD

**Issue by ikreymer** [webrecorder/webrecorder#322]
Support uploading HAR (HTTP Archive) into Webrecorder by converting to WARCs on the fly using `har2warc`

**Comment by edsu** [comment]
I'm just curious to know more about the use case that motivated this. Were there users generating HAR files in another tool who wanted to upload them?

Also, thanks for splitting out har2warc as a separate tool!

**Comment by ikreymer** [comment]
Hey @edsu , sorry forgot to respond earlier. There wasn't any one particular use case, but was reminded of the HAR format by this thread: https://twitter.com/webrecorder_io/status/841743910359597056

I didn't realize HAR kept request/response log, and so thought it may be nice to have HAR->WARC converter, that's how har2warc came about. I think its just yet another tool for approaching high-fidelity archiving (though HAR does not store binary request payload, eg. POST)

Some possible use cases:
- Testing/debugging "native" browser traffic vs recorded via Webrecorder to check for any differences or peculiarities.
- http/2 traffic is written to HAR, replay of http/2 content as http1.1
- Webrecorder Player compatibility with tools that produce/operate on HARs

**Comment by ikreymer** [comment]
HAR support now available both on https://webrecorder.io/ and in Webrecorder Player
