### ISSUE TITLE
wix gallery sites do not play back correctly

### ISSUE THREAD

**Issue by 2600box** [webrecorder/webrecorder#334]
example: http://www.skullavera.com/fullscreen-page/

webrecorder downloads files, but because they do not have standard names like image1.jpg but instead an url like `https://static.wixstatic.com/media/e17e21_b0fa29e81c5940cbb7422c4790c7d65c~mv2.png/v1/fill/w_422,h_478,al_c,usm_0.66_1.00_0.01/e17e21_b0fa29e81c5940cbb7422c4790c7d65c~mv2.png` it breaks

**Comment by ikreymer** [comment]
Not sure what you mean exactly.. the urls should be recorded either way.
However, the url you included appears to be broken even with without WR, so not much we can do.

![screen shot 2017-04-15 at 7 15 30 pm](https://cloud.githubusercontent.com/assets/1015759/25068175/f05583ee-220f-11e7-87d6-6a87b9a9c391.png)
