### ISSUE TITLE
Weird behavior of size counter when recording large video

### ISSUE THREAD

**Issue by despens** [webrecorder/webrecorder#337]
When recording large video like here:

http://www.daserste.de/information/reportage-dokumentation/dokus/videos/nervoese-republik-ein-jahr-deutschland-politiker-video-104.html

…when skipping around, the size counter is suddenly decreasing. In my case, from 1.56GB down to 822MB, then going back up to 1.62GB, then going down to 656MB.

**Comment by m4rk3r** [comment]
I believe the new size counter, utilizing pending size, should help address this. Mind reopening if you experience again?
