### ISSUE TITLE
ImportError: No module named beaker.middleware

### ISSUE THREAD

**Issue by petekmpf** [webrecorder/webrecorder#35]
I'm totally new to docker, so it could just be me.  But when following the instructions
https://github.com/webrecorder/webrecorder
I got as far as docker-compose up, and attempted to access the site http://mysite:8089 and received Internal Server Error.  Checked the docker console and found this error:
webrecorder_1 | *** Operational MODE: preforking+threaded ***
webrecorder_1 | Traceback (most recent call last):
webrecorder_1 |   File "./main.py", line 1, in <module>
webrecorder_1 |     from app import init
webrecorder_1 |   File "./app.py", line 15, in <module>
webrecorder_1 |     from manager import init_cork, CollsManager, ValidationException
webrecorder_1 |   File "./manager.py", line 3, in <module>
webrecorder_1 |     from beaker.middleware import SessionMiddleware
webrecorder_1 | ImportError: No module named beaker.middleware
webrecorder_1 | unable to load app 0 (mountpoint='') (callable not found or import error)
webrecorder_1 | *** no app loaded. going in full dynamic mode ***
webrecorder_1 | *** uWSGI is running in multiple interpreter mode ***

When I hit the site it reported this in the console
webrecorder_1 | --- no python application found, check your startup logs for errors ---
webrecorder_1 | [pid: 17|app: -1|req: -1/1] 69.117.167.62 () {46 vars in 751 bytes} [Thu Mar 10 14:35:48 2016] GET / => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
nginx_1       | 69.117.167.62 - - [10/Mar/2016:14:35:48 +0000] "GET / HTTP/1.1" 500 32 "-" "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.116 Safari/537.36"

Again I apologize for my general ignorance.  I'm going to do my best to find out where beaker.middleware should be in the docker build, but I'm also a complete novice at python :)

**Comment by petekmpf** [comment]
I did get past this issue, but sadly I'm not entirely sure how.  I tried connecting to the docker instance and used pip install beaker.  Then I quit the image, re-started it.  Where I go fuzzy is that I think I re-ran the docker-compose build and up again at some point.  Either way, it is working.  I may try a new linux server to see if the same behavior persists.

**Comment by ikreymer** [comment]
Thanks for letting us know, for whatever reason, it was not explicitly in the requirements so I added it.. It may have been installed through a dependency implicitly before. Anyway, should work more consistently now.
