### ISSUE TITLE
Collection descriptions markdown wrongly escaped

### ISSUE THREAD

**Issue by despens** [webrecorder/webrecorder#357]
Wanted to put a quotation into the description of a collection via markdown:

```markdown
Text before quote

> This is a quote

Text after quote
```

During editing, the markdown preview displays the quote correctly.

After saving, the `>` is being shown when the markdown is rendered, instead of showing the paragraph as a quote. Editing the description again reveals that the character had been escaped to `&gt;`;

#### during editing
![selection_999 499](https://cloud.githubusercontent.com/assets/571494/26669918/eafd1bcc-46af-11e7-9e71-7b10ef98ff4f.png)

#### after saving

![selection_999 498](https://cloud.githubusercontent.com/assets/571494/26669931/f61f513c-46af-11e7-91ac-f8262ae70b8d.png)

![selection_999 500](https://cloud.githubusercontent.com/assets/571494/26669935/f9fe56a4-46af-11e7-839d-3e841edb85cd.png)

**Comment by m4rk3r** [comment]
Fixed by new editor
