### ISSUE TITLE
Issues with high numbers of bookmarks

### ISSUE THREAD

**Issue by despens** [webrecorder/webrecorder#360]
When renaming a recording with several hundred bookmarks, renaming the recording causes significant delays in rendering the list, which makes it appear as if data is lost.

After a minute or so, in which the interface is operable, the bookmarks re-appear. 

Clicking filters on and off can take a minute to update the bookmark list.

Test collection: https://webrecorder.io/despens/compressed-moons

**Comment by m4rk3r** [comment]
Fixed by new release
