### ISSUE TITLE
Redirection issues with recording doodle.com

### ISSUE THREAD

**Issue by despens** [webrecorder/webrecorder#383]
https://twitter.com/shinajya/status/883379033098129408

![selection_999 644](https://user-images.githubusercontent.com/571494/27970157-0aef29c4-634e-11e7-9971-48f0729c006d.png)

**Comment by ikreymer** [comment]
Fixed by proxy mode update in pywb (https://github.com/ikreymer/pywb/commit/925f8337a5fcc3f421158525453dc2f67edcc91e) which should fix the redirect issues (no longer rewriting http<->https)
Confirmed fixed with Doodle in both Chrome and FF.
