### ISSUE TITLE
Landing Page Design Refresh Wires 

### ISSUE THREAD

**Issue by patshiu** [webrecorder/webrecorder#405]
**Objectives:** 
- Make the benefits of using webrecorder immediately clear — users should not be confused about why webrecorder is useful 

**Other notes:** 
- Page is about webrecorder, not Web Archives, but we should foreshadow some notion of Web Archives for the uninitiated. 
- Images are placeholders. Style & images to be developed later. 

  
![r1_webrecorder_landing_mockup](https://user-images.githubusercontent.com/3271403/28789165-30536f3e-75f2-11e7-9c63-9a0f63299a07.png)

  
  
  
------------------------------------
   
On scrolling down, the top section "minifies" to become a sticky top bar: 
![r1_webrecorder_landing_mockup-scroll_down](https://user-images.githubusercontent.com/3271403/28789190-514ced46-75f2-11e7-8d12-981bb5f29907.png)

**Comment by m4rk3r** [comment]
implemented
