### ISSUE TITLE
Cannot extract page at a certain date

### ISSUE THREAD

**Issue by despens** [webrecorder/webrecorder#407]
When trying to extract https://web.archive.org/web/20030216230918/http://www.turbulence.org/ Webrecorder always records at another date from 4 months earlier:

![selection_00031](https://user-images.githubusercontent.com/571494/28907408-68850dda-781e-11e7-9973-2f3e74828e0b.png)

**Comment by m4rk3r** [comment]
https://webrecorder.io/m4rk3r/test/20030216230918/http://www.turbulence.org/

Appears to be fixed!
