### ISSUE TITLE
ajax call not recorded (trello)

### ISSUE THREAD

**Issue by seamang** [webrecorder/webrecorder#408]
I'm experimenting with archiving a trello board. Comments on cards (pulled down separately using Ajax) get a 404 on playback. The Ajax URL is constant; it includes a hex string, but this doesn't change across accesses so I would have thought webrecorder should cope with it.

Here's an example which gives a 404 on playback:

 http://localhost:8089/temp!OULEFU4T/temp/20170810154755mp_/https://trello.com/1/cards/57a1c6f52b5fa5ad17809c6c?actions=addAttachmentToCard%2CaddChecklistToCard%2CaddMemberToCard%2CcommentCard%2CcopyCommentCard%2CconvertToCardFromCheckItem%2CcreateCard%2CcopyCard%2CdeleteAttachmentFromCard%2CemailCard%2CmoveCardFromBoard%2CmoveCardToBoard%2CremoveChecklistFromCard%2CremoveMemberFromCard%2CupdateCard%3AidList%2CupdateCard%3Aclosed%2CupdateCard%3Adue%2CupdateCard%3AdueComplete%2CupdateCheckItemStateOnCard&actions_display=true&action_memberCreator_fields=fullName%2Cinitials%2CidEnterprise%2CmemberType%2Cusername%2CavatarHash%2Cbio%2CbioData%2Cconfirmed%2Cproducts%2Curl%2CidPremOrgsAdmin&members=true&member_fields=fullName%2Cinitials%2CidEnterprise%2CmemberType%2Cusername%2CavatarHash%2Cbio%2CbioData%2Cconfirmed%2Cproducts%2Curl%2Cstatus&attachments=true&fields=email&checklists=all&list=true&pluginData=true&actions_limit=50

**Comment by seamang** [comment]
A colleague has noticed that this problem is only present in Firefox; recording and playback using Chrome is OK.

**Comment by ikreymer** [comment]
Think I found the cause, the WebSocket connection is blocked by the CSP policy. For whatever reason, in Chrome this is ok, but in Firefox this throws an exception that breaks the page.
For now, allowed 'live leaking' of WS connections, since they are not currently recorded anyway, to allow situations like this. This is now deployed on webrecorder.io, and I've tested with a few Trello boards in FF. Can you confirm if this fixes the issue for you @seamang ?
If so, will merge the fix. Thanks

**Comment by ikreymer** [comment]
And thanks for the key feedback that this was in Firefox only, as I was testing primarily in Chrome until then!

**Comment by seamang** [comment]
I'm afraid it's still not working for me. I have tried from two hosts: one running CentOS 7.3.1611, the other Gentoo stable. 

The screenshot shows a card with the comments not displayed. It looks like there is a leak to the live trello.com on playback, I don't know if this is related.

![trello_playback](https://user-images.githubusercontent.com/4570502/30958928-8cb0ed34-a436-11e7-9d5a-ef696d2349c8.png)

**Comment by ikreymer** [comment]
The live leak is the Websocket connection, that was just enabled. Without it, I wasn't able to record Trello at all in Firefox. Unfortunately, I haven't been able to repro this issue -- tried with another private Trello board and was able to record and replay after logging, in Firefox. However, this was with Firefox 55 on OSX
