### ISSUE TITLE
Issues with "Record this URL again"

### ISSUE THREAD

**Issue by despens** [webrecorder/webrecorder#419]
Trying to re-record a [URL from one of my collections](https://webrecorder.io/despens/twtr/20170902141035/https://twitter.com/Relive44/status/903660328273281029), the **Record This URL again** function produced weird behavior:

- The mode indicator button didn't change to "recording", flickers mouse-over
- It seems impossible to leave the page, neither by clicking any links nor the "stop" button
- No recordings are created

![wrbug](https://user-images.githubusercontent.com/571494/30167596-35122fc0-93e7-11e7-884a-9fc3d3c735d5.gif)

**Comment by m4rk3r** [comment]
This is hopefully fixed by new UI, please reopen if you encounter again : )
