### ISSUE TITLE
MathJax formula does not render correctly

### ISSUE THREAD

**Issue by shakkhar** [webrecorder/webrecorder#428]
I was trying to archive this page: https://www.datacamp.com/community/tutorials/finance-python-trading. There is a formula near the end which is rendered using MathJax library. On the original site, it renders like this:
![fireshot capture 8 - python for finance_ algorithmic tradin_ - https___www datacamp com_community_](https://user-images.githubusercontent.com/692872/31858062-75a95ca0-b6bc-11e7-9b83-478753aea265.png)

When I loaded the page in Webrecorder, the same formula looks like this:
![fireshot capture 9 - python for finance_ algorithmic tradin_ - http___optiplex local_8089_shakkhar](https://user-images.githubusercontent.com/692872/31858067-9bfa11b0-b6bc-11e7-8ce3-80bedc8df913.png)

I am not sure if that is the expected behavior. I am running git hash 3ee66e8d2480adb7aa152fc3f7de853a22cce6b3. Let me know if I can help with any other information.

**Comment by ikreymer** [comment]
This isn't happening on the latest at webrecorder.io, but is likely related to this that was fixed upstream in the pywb library.

Can you try pulling the latest pywb container with `docker pull webrecorder/pywb`, and then rebuilding Webrecorder with `docker-compose build; docker-compose up -d` and see if that fixes the issue for you?

**Comment by shakkhar** [comment]
Indeed it has been fixed. Thanks for looking into this.
