### ISSUE TITLE
Support email doesn't propagate site

### ISSUE THREAD

**Issue by webster** [webrecorder/webrecorder#432]
Setting SUPPORT_EMAIL in wr.env does not propagate the site. 

For example, the "Your account is out of space" message has a contact us link, which is set to support@webrecorder.io, even if SUPPORT_EMAIL is set.

As another example, the contact link in the global footer is set to mailto:support@webrecorder.io, again even if SUPPORT_EMAIL is set.

**Comment by ikreymer** [comment]
Thanks for letting us know about this also. We're working on a UI update and hope to make Webrecorder more customizable soon. Currently, the SUPPORT_EMAIL var is specifically for bug reporting, but can be made more general.

Just wondering, are you planning on deploying a hosted instance of Webrecorder for others to use?

**Comment by m4rk3r** [comment]
The support email is now configurable in the new UI in `config.js`, thanks again for reporting.
