### ISSUE TITLE
Finish the 'All Versions' of a page (timemap view)

### ISSUE THREAD

**Issue by ikreymer** [webrecorder/webrecorder#44]
Finish the design for the 'all versions' of a URL view, eg. calendar or star query, `webrecorder.io/user/coll/*/http://example.com/`

Include in-bound navigation to this view.

**Comment by ikreymer** [comment]
Well, this is working good enough for now... could add a link back to the collection or recording.. or maybe we punt this from the release, and add to next cycle? This would be part of a larger search system.. (or could add an 'all versions' link on the bookmarks page)

**Comment by despens** [comment]
The column "From Recording" should not link to the archived URL within that recording, but to the collection page with that recording set as a filter parameter

**Comment by ikreymer** [comment]
Fixed. This page is good enough for now, will be superseded by improved search functionality later.
