### ISSUE TITLE
Create Nectar ads for Webrecorder

### ISSUE THREAD

**Issue by michaelconnor** [webrecorder/webrecorder#441]
This is a request for Webrecorder that can be served when ad sales on Rhiz.org are slow. There are probably going to be gaps over the holidays!

Billboard (970×250)
Half Page (300×600)
Tablet Leaderboard (728×90 / 970×90)
Email Newsletter Banners (600×400)

**Comment by ikreymer** [comment]
Closing, this is not the right place for this issue.
