### ISSUE TITLE
Home link in breadcrumb navigation doesn't underline on hover

### ISSUE THREAD

**Issue by despens** [webrecorder/webrecorder#449]
I applaud that the "Webrecorder" link in the breadcrumb nav is inactive when on the home page. Yet on any deeper URL, it is the only link in the breadcrumbs that doesn't underline on hover.

Would also want to suggest to change the links `title` attribute to `Webrecorder home page` instead of `Return...` because users might not return but see it for the first time.

**Comment by patshiu** [comment]
Ok fixed both! https://github.com/webrecorder/webrecorder/commit/d2517c48bc8812eafc4b56525fd1c812499a0675 Thanks dragan for spotting this. 

@m4rk3r can we update the live page pls?

**Comment by patshiu** [comment]
There's also a small fix in there for a typo on "webpage" -> "web page" that anna found. :)

**Comment by m4rk3r** [comment]
Thanks @patshiu will update shortly!
