### ISSUE TITLE
Issue when using url as recording name..

### ISSUE THREAD

**Issue by DuckHP** [webrecorder/webrecorder#456]
If entering the/an url to record as recording name, that will apparently _seriously_ break the recording(s) or at very least the playback of it. _(the url entered in name field will also be visible in the url to record-field during recording. With no visible problem indication during recording), **The problem will first arise when trying to play back the recorded WARCs afterwards.**_ 

Noticed this when having hastily copy-pasted an url into both fields, thinking it would be fine, then deciding to download the warc from _webrecorder.io_ and uploading it to my local one.

It will cause **'Resource not Found'** to show when trying to play-back the WARC, and trying to patch it using webrecorder will not work.

How to replicate: Paste the url (or any url?) into recording name field..

Perhaps an idea would be to implement formatting to invalidate any url's put into recording-name field?

Anyway, just a heads up.

**Comment by m4rk3r** [comment]
Thanks for reporting this issue. We've made some changes that no longer make this issue relevant, but will keep an eye out for issues like this in the future.
