### ISSUE TITLE
Create tagline/slogan!

### ISSUE THREAD

**Issue by ikreymer** [webrecorder/webrecorder#49]
Evaluate
"An open source web archiving platform and service for all!
Easily create high-fidelity, standards compliant archives of the web as you browse."

**Comment by michaelconnor** [comment]
Do we need platform AND service? Both words are used so broadly already
maybe we can choose one.

On Wednesday, April 20, 2016, Ilya Kreymer <notifications@github.com> wrote:

> Evaluate
> "An open source web archiving platform and service for all!
> Easily create high-fidelity, standards compliant archives of the web as
> you browse."
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/webrecorder/webrecorder/issues/49>
>


-- 
--

Michael Connor
Artistic Director
Rhizome
at the New Museum
235 Bowery
New York, NY 10002
http://www.rhizome.org

**Comment by harlantwood** [comment]
**Webrecorder: Your Personal Internet Archive**

An open source web archiving solution: easily create rich, standards compliant archives of the web as you browse.

**Comment by harlantwood** [comment]
Hm, my version uses variations of the word "archive" 3 times.

Was also thinking "Your Personal Wayback Machine".  But not sure if that's true?
