### ISSUE TITLE
Markdown editor: clicking "save" doesn't do anything

### ISSUE THREAD

**Issue by mashalifshin** [webrecorder/webrecorder#50]
"I can enter text in the text editor box, but Clicking Save doesn’t take me anywhere else.  I seem to be stuck at the text editor box.  Oh I see, that happens from Preview. If I exit Preview and then click Save, it is Saved, and I can see my new description."

**Comment by ikreymer** [comment]
Yeah, for some reason the markdown editor disables the save button when in preview mode.. This may not be very clear, and imo, no good reason for it. I'll see if there's a way to not do that, otherwise, can add a custom Save button.
