### ISSUE TITLE
'Add to recording' workflow improvement

### ISSUE THREAD

**Issue by mashalifshin** [webrecorder/webrecorder#54]
Should url bar combobox be enabled for 'add to recording' as well?

"We need to think about the "add to recording" workflow again i'd say, it seems to appear in weird places and sometimes requires an extra click that doesn't seem to make that much sense..."

**Comment by mashalifshin** [comment]
Add to recording will be a step available only from the browsing context.  It will be clearly differentiated from browsing and regular recording mode.

**Comment by mashalifshin** [comment]
Add to recording
- this is an operation available on a per-recording basis
- this mode allows arbitrary browsing and adding of new pages to a recording

Patch mode:
- patching is an operation that is available only on a per-page basis
- patch mode is accessed when browsing a page, or as an action when viewing a list of pages
- in patch mode, you can  interact with the page you are patching, but the url bar is not available for loading other pages.  there is a control to exit patch mode and return to browsing to verify the patched page.
- if you click a link and load a new page in patch mode, that's okay because  the new page will be recorded as though it's in record mode

Ilya was saying entering patch mode should only be available when browsing a page, and not available as an action from the page list ... thoughts?

**Comment by ikreymer** [comment]
Yes, this sounds good. The reason I'd like to only have patch mode available from the replay is that it should be entered only when a user visits a page, sees that something is missing, and decides to patch. If it is also listed on the page list, it may be confused for browsing.

Also, the patching option should only be available when you are the owner (logged-in or anonymous) and not browsing someone else's collection.
