### ISSUE TITLE
record youtube

### ISSUE THREAD

**Issue by jotjot** [webrecorder/webrecorder#542]
I have been trying to record a youtube video but it always fails: 
https://www.youtube.com/watch?v=ObTJK4Bvvso

![screen shot 2018-06-06 at 09 40 25](https://user-images.githubusercontent.com/2178333/41038633-3bf451a4-696d-11e8-98f3-20bce6aa4e06.png)

**Comment by ikreymer** [comment]
Which browser and OS are you using? Webrecorder works best with Chrome and Firefox. I was not able to repro the issue with Chrome or Firefox.

**Comment by jotjot** [comment]
I had the problem using Safari. I can confirm that it works on Chrome. Sorry, it was not clear to me that it works best on Chrome and Firefox.

**Comment by ikreymer** [comment]
No problem, its on us to communicate this better!
