### ISSUE TITLE
Non-ASCII characters in URLs/Links

### ISSUE THREAD

**Issue by despens** [webrecorder/webrecorder#585]
[This page](http://wespenberater.de/infos-und-aktionen.html)  contains a link to http://www.naturpädagogik-ahlborn.de/naturspiele.html (note umlaut in domain name).

In Webrecorder, the link is appearing as http://www.naturp%C3%A3%C2%A4dagogik-ahlborn.de/naturspiele.html and rendered with two characters. See https://webrecorder.io/despens/der-wespenberater/20180807095712/http://wespenberater.de/infos-und-aktionen.html (Scroll down to "die Wabenbaustelle")

![selection_999 792](https://user-images.githubusercontent.com/571494/43769997-66f91c5a-9a3b-11e8-93a3-848afddc2b40.png)

**Comment by N0taN3rd** [comment]
@despens non-ascii character URL rewriting fix was just merged into pywb develop branch https://github.com/webrecorder/pywb/pull/361
This issue should be resolved resolved shortly.

**Comment by despens** [comment]
This works now! Great work!
