### ISSUE TITLE
Cover page - Hide "Lists in this Collection" if no lists exist

### ISSUE THREAD

**Issue by kgrons** [webrecorder/webrecorder#590]
If no lists exist in a Collection, the header "Lists in this Collection" could be hidden on the Cover screen (because the field is not populated)?

**Comment by patshiu** [comment]
Thanks @kgrons, will keep this in mind. We're currently working on improving the cover page which should be ready in a few weeks, it certainly is a bit of an odd state at the moment!

**Comment by m4rk3r** [comment]
Updated this, thanks!
