### ISSUE TITLE
Unable to archive with local deployment

### ISSUE THREAD

**Issue by Serkan-devel** [webrecorder/webrecorder#614]
![2018-09-30-115353_1600x900_scrot](https://user-images.githubusercontent.com/16866642/46256195-9e58c380-c4a7-11e8-95c7-69fd0ebc524e.png)

Following [this guide](https://github.com/webrecorder/webrecorder#running-locally) on debian testing and `Docker version 18.06.0-ce, build 0ffa825` doesn't let me archive anything.

Here are some logs from the containers:
[webrecorder_app_1-log.txt](https://github.com/webrecorder/webrecorder/files/2431426/webrecorder_app_1-log.txt)

[webrecorder_nginx_1-log.txt](https://github.com/webrecorder/webrecorder/files/2431427/webrecorder_nginx_1-log.txt)

[webrecorder_frontend_1-log.txt](https://github.com/webrecorder/webrecorder/files/2431429/webrecorder_frontend_1-log.txt)

**Comment by ikreymer** [comment]
Sorry about that, I think the base pywb Docker image is out of date. Webrecorder works with the pywb develop branch as the pywb release are generally a bit slower, so this is likely the issue

Can you try changing the `FROM` line in the Dockerfile to be `FROM webrecorder/pywb:develop` and confirm if that works? If so, we'll just switch it to use the develop image.

**Comment by Serkan-devel** [comment]
So I've renamed it to `FROM webrecorder/pywb:develop` and ran `docker-compose build` on the root folder of the repo, then `docker-compose up -d` and got this
![2018-10-01-110419_1600x900_scrot](https://user-images.githubusercontent.com/16866642/46279688-1f788f00-c56a-11e8-8a38-31e7476ce36f.png)

These are the logs now
[webrecorder_app_1-logs2.txt](https://github.com/webrecorder/webrecorder/files/2433372/webrecorder_app_1-logs2.txt)
[webrecorder_redis_1-logs2.txt](https://github.com/webrecorder/webrecorder/files/2433373/webrecorder_redis_1-logs2.txt)
[webrecorder_warcserver_1-logs2.txt](https://github.com/webrecorder/webrecorder/files/2433376/webrecorder_warcserver_1-logs2.txt)
[webrecorder_recorder_1-logs2.txt](https://github.com/webrecorder/webrecorder/files/2433378/webrecorder_recorder_1-logs2.txt)
[webrecorder_nginx_1-logs2.txt](https://github.com/webrecorder/webrecorder/files/2433381/webrecorder_nginx_1-logs2.txt)
[webrecorder_frontend_1-logs2.txt](https://github.com/webrecorder/webrecorder/files/2433382/webrecorder_frontend_1-logs2.txt)
[webrecorder_dat_1-logs2.txt](https://github.com/webrecorder/webrecorder/files/2433384/webrecorder_dat_1-logs2.txt)

**Comment by m4rk3r** [comment]
Hm, the logs seem to be ok, did you give it a minute before loading? The frontend can take around a minute or so to build.

**Comment by Serkan-devel** [comment]
It works thanks!
