### ISSUE TITLE
How to remove email verification and nginx for local deployment

### ISSUE THREAD

**Issue by Serkan-devel** [webrecorder/webrecorder#616]
I'm trying to use webrecorder locally within a LAN, but trying to archive a page requires me to sign-in with an email even though I have full control over the environment. Is there a way to disable email verification and just use the archiver?

Also, nginx seems to be more of an overhead than actually useful. Is there a way to access the frontend directly from the browser?

**Comment by Serkan-devel** [comment]
For some reason I, neither do I get an email verification from the sign up page, nor can I create an account manually

some logs are here
[webrecorder_nginx_1-logs3.txt](https://github.com/webrecorder/webrecorder/files/2437502/webrecorder_nginx_1-logs3.txt)
[webrecorder_frontend_1-logs3.txt](https://github.com/webrecorder/webrecorder/files/2437503/webrecorder_frontend_1-logs3.txt)
[webrecorder_app_1-logs3.txt](https://github.com/webrecorder/webrecorder/files/2437505/webrecorder_app_1-logs3.txt)
[webrecorder_mailserver_1-logs3.txt](https://github.com/webrecorder/webrecorder/files/2437506/webrecorder_mailserver_1-logs3.txt)

Is there a way to just disable the account logic entirely?

**Comment by deliciouslytyped** [comment]
I solved the user validation annoyance in a really hacky way by patching webrecorder/webrecorder/models/usermanager.py , and using the CLI user admin tool mentioned in the readme. In hindsight this may have been unnecessary because from a superficial look, it seem like the email validation like this is just syntactic.
