### ISSUE TITLE
Instagram recording

### ISSUE THREAD

**Issue by ikreymer** [webrecorder/webrecorder#64]
"I recorded: https://www.instagram.com/sfmoma/. Couldn’t get the 2nd page of posts to load w/in Webrec. They loaded fine just from insta site.  I tried a couple times and couldn’t get it to work. “Load More” just won’t load more." -Morgan

May be due to JSON-based navigation optimization.

**Comment by peterk** [comment]
Looking at the Warc file with warcdump it seems to have recorded the images that are required for playback. Maybe there is a script interfering?

**Comment by ikreymer** [comment]
This original issue is pretty old, and likely improvements have been made there.
However, I think the new issue is due to Instagram's use of `<img srcset>`.
Likely what is happening is that you are viewing the Instagram replay at a slightly different resolution then was recorded, so its choosing a different set of images. To confirm, try resizing the player window (to make it similar to what was when recording) and reloading the page.

We are looking at ways to address this, such as by capturing all of the images in the `srcset`

**Comment by peterk** [comment]
Ah of course. I was using Webrecorder Player on my high-DPI macbook. Launching Webrecorder Player in "low resolution mode" makes playback work properly (resizing makes no difference). Would be great if srcset resources were archived as well.
