### ISSUE TITLE
Text formatting in Description field

### ISSUE THREAD

**Issue by kgrons** [webrecorder/webrecorder#655]
Related to issue #1789 (submitted via webrecorder bug interface).

Anna requested we submit the results of our test as it relates to incorrect numbering when using Markdown in the Description field, for numbered entries that contain sub-bullets. Working with @lmbarrier to test if plain text numbering is retained when pasted into a List Description field:

- Using a source .txt, I copy and pasted a numbered list into the Webrecorder List Description field
- I clicked Save

- In the Description field, the lists begin at 1 for each entry.

**Comment by m4rk3r** [comment]
Hi @kgrons thanks opening the issue! Just so that we're working with the same source text, could you provide an example of what you're inputting to reach this bug?

**Comment by kgrons** [comment]
[sampleplaintext.txt](https://github.com/webrecorder/webrecorder/files/2641043/sampleplaintext.txt)

Attaching the numbered list we used as the source. Thanks!

**Comment by m4rk3r** [comment]
Ah, so looking at the [markdown spec for lists](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#lists) there doesn't seem to be a clear way to format text in that manner, oddly. You can kind of fake it by doing something like:
```
1. heading··
··\- a fake sublist··
··\- a secondfake sublist··
··\- the last fake sublist
2. 2nd heading··
··\- etc etc··
```
with `·` designating spaces.. I gave that a shot on this [demo collection](https://webrecorder.io/m4rk3r/demo) with the document you shared, and [here is the raw markdown](https://gist.github.com/m4rk3r/3cde48613279b078a87013bccbd6f3d1)

Admit this is very fiddly! We'll try to look to help make formatting easier, but does this help for the time being?

**Comment by kgrons** [comment]
Yes, thanks so much for reformatting the entire thing for us. We were able to successfully add your modified text to the description in our webrecorder account and have it display correctly.

**Comment by m4rk3r** [comment]
Ok, great to hear!
