### ISSUE TITLE
What's the basic recording capabilities of pywb different from webrecorder?

### ISSUE THREAD

**Issue by hanoii** [webrecorder/webrecorder#665]
According the the README:

> Finally, for users interested in the core "replay system" and very basic recording capabilities, deploying pywb could also make sense. Webrecorder is built on top of pywb (Python Wayback/Python Web Archive Toolkit), and the core recording and replay functionality is provided by pywb as a standalone Python library. pywb comes with a Docker image as well.

What would be the non-basic recording capabilities that webrecorder adds and what's the tool that adds it?

**Comment by ikreymer** [comment]
Good question! Mostly extraction and patching, which are also done via pywb but require a custom configuration. Extraction allows extracting content from existing archives and recording to WARCs, while patching provides ability to patch only what's missing, either from live web or from other archives. Here's a release we had about extraction + patching: http://rhizome.org/editorial/2017/jul/12/webrecorder-announcement/

Another aspect that the webrecorder system adds is the remote browser system, which allows you to capture not only using your browser, but one of the preconfigured browsers you have available. We have a few versions of Chrome and Firefox that support Flash for example, which you could use to capture websites containing Flash.

Probably something we should add to the docs
