### ISSUE TITLE
recursive redirect with current browser

### ISSUE THREAD

**Issue by friedz** [webrecorder/webrecorder#672]
wenn using the current browser `mp_/<site>` pages are redirected to `<site>` wich in turn will then load `mp_/mp_/<site>` an so on.
i am pretty shure this comes somhow from pywb but i cant find my mistake.

This does not happen wen using a remote browser.

![Recusive redirect](https://user-images.githubusercontent.com/2459232/52419560-a6c5a880-2af0-11e9-96a6-0d3a109571cd.PNG)

**Comment by ikreymer** [comment]
To confirm, you're seeing this on a local instance of Webrecorder, not webrecorder.io, right?

**Comment by friedz** [comment]
Yes it`s a local instance, with some modifications done.

**Comment by ikreymer** [comment]
Do you have `APP_HOST` and `CONTENT_HOST` env variables set in your wr.env?
If so, try clearing them, eg. `APP_HOST=` and `CONTENT_HOST=` and access through `localhost:8089`. Are you trying to configure WR with a custom domain?
Have you modified any other settings, and if so, would you be able to share them so can better diagnose the issue?

**Comment by friedz** [comment]
No `APP_HOST` and `CONTENT_HOST` are not set. sadly right now i don't know exactly what is all changed in our version. But i worked around the problem by getting the current version of Webrecorder and starting to carefully migrate our changes.
