### ISSUE TITLE
why WARC instead of other format such as MHTML

### ISSUE THREAD

**Issue by johnss** [webrecorder/webrecorder#684]
please can devs give me a reason why warc is chosen as a supported import format instead of other format, i think warc should not be used because of very little popularity compared to other archive format such as mhtml, nearly all browser understand mht especially webkit based browser and its fork blink support creating and reading, while to my knowledge no single browser that support creating warc even just reading warc is very rare, and if possible it must install an extension, while mht is possible out the box, and moreover is more portable meaning it is can be created and read through mobile and desktop browser both chrome mobile and desktop support mht, while warc is usually desktop only, and because more traffic are from mobile than desktop please consider adding support for mht import

**Comment by ikreymer** [comment]
WARC allows for representing network traffic, not just static resources as they are on a page, which allows for replay of dynamic content. For example, with WARC we can replay dynamic pages that use JS to load additional resources, amongst many other things. I don't think this would be possible with MHTML, which is not really conducive to the type of archiving that Webrecorder is trying to support. It may be possible to create a WARC->MHTML converted in some way by rendering the page in a browser and saving it as MHTML...

**Comment by johnss** [comment]
i need MHTML to WARC converter because i use android & chrome, nearly all my saved pages is in MHT, is there any plans to create it?
