### ISSUE TITLE
Facebook recording issues

### ISSUE THREAD

**Issue by ikreymer** [webrecorder/webrecorder#69]
Ensure photo albums can be recorded.
May wait till containerized browser support is fully implemented.

**Comment by ikreymer** [comment]
The remaining issues are likely related to cookies and cookie domain settings

**Comment by m4rk3r** [comment]
Thanks to the hard work of @ikreymer @N0taN3rd support for facebook has vastly improved, should track particular issues in separate issues.

**Comment by laurelin88** [comment]
Hello all,
I did not want to open another issue for this as it is not something new but I was not sure where else to ask!
I don't have much coding experience (almost none, tbh) but do you think you could explain in a few words why Webrecorder cannot capture Facebook, and especially photos?
I am using it to record a Facebook page (it is also unpublished at the moment, and I am accessing it as admin, if that makes any difference) and it seems to completely skip the Photos tab every time I try to record it; nothing not even thumbnails!
I also tried to open some Facebook events included in that page as separate links, and a few seconds after I scroll down on each of them, the session times and stops..?

I know this is not a troubleshooting page, and I am not looking for immediate solutions or something like that :) I just would like to understand a bit more about the workings of Webrecorder!
