### ISSUE TITLE
Figure out treatment for communicating "space remaining" across the app

### ISSUE THREAD

**Issue by mashalifshin** [webrecorder/webrecorder#70]

**Comment by mashalifshin** [comment]
This includes figuring out a consistent, easily grasped way to show space usage:
- during recording
- on the collection info page
- on the recording info page

The goals are:
- clear messaging
- a visual way to grasp space used vs space remaining
- reduce anxiety about running out of space

**Comment by mashalifshin** [comment]
Proposed changes:

- In the recorder, continue to show a running size counter
- On the recording page, change label from "space used" to "size" and show a number
- On the collection page, change label from "space used" to "size" and show a number
- On the archive page, show "space used" label and a number, as well as little progress bar like this:
![space](https://cloud.githubusercontent.com/assets/709758/14837212/361df2c8-0bcb-11e6-8352-9ff9e0b4cbee.jpg)

The diagram shows 3 different states, a green progress bar for lots of space left, a yellow one for when you should start thinking about space, and a red one for when you're almost out.  We could also use the standard flash message to say "You're running low on space -- request more" or something similar when they are getting close.

In this design, we don't show them how much space they get.  This leaves us free to change that at will for all users, but might be anxiety provoking.  If we want to message how much space is available up front, the progress bar label can show "30MB / 3 GB" instead of just "30 MB".

Still left to figure out:
- What happens when someone is recording and they are about to run out of space?  I think it would be nice to let people finish the current recording session, even if it runs over the allotment, but stop them from recording anything else.  What does the app do currently?

**Comment by ikreymer** [comment]
I like the progress bar.
Should it also appear on the recording page, along with the size counter, if there is space?
It could have the text over the progress bar.

> What happens when someone is recording and they are about to run out of space? I think it would be nice to let people finish the current recording session, even if it runs over the allotment, but stop them from recording anything else. What does the app do currently?

I think it should stop recording from the point that the space has been reached, but still load the page. Since a session doesn't have a defined end, that would be tricky. Any files currently loading would get recorded though, so its possible to sneak in a large file at the end still.

I believe that in the current version, the grey background of the size indicator turns red and an out of space message is added to it.

**Comment by mashalifshin** [comment]
I wanted the text to appear on the progress bar, but that seems to invariably look confusing, as the text interferes with the filled area boundary of the progress bar (our text label is always relatively long), plus it's two pieces of information to interpret in one visual area, so in code checked in now they are separate lines.  

I think that may be enough of a reason not to do it in the recorder for now, that we don't have the space for a two separate lines.  I have some other reasons but I'll spare you unless you wanna know :-)

So for running out of space during recording:
- When they're getting close to running out of space, show a message
- When they're out of space, redirect them to the recording info page
- Prevent them from recording if they are out of space and try to record
