### ISSUE TITLE
Collection is empty after archiving

### ISSUE THREAD

**Issue by Feribv** [webrecorder/webrecorder#736]
Hello,
I managed to setup webrecorder on Ubuntu 18. 
I have a small issue though. After archiving a page in the default collection (or a newly created collection), when you stop capturing, no collection is shown. The Pages list is (and remains) emtpy.
I use this URL: http://192.168.0.223:8089/testuser/default-collection/

Where should I look to debug this issue?

All the docker components are started up:
CONTAINER ID        IMAGE                          COMMAND                  CREATED             STATUS              PORTS                                                      NAMES
fe12e68c0709        webrecorder/nginx              "nginx -g 'daemon of…"   40 minutes ago      Up 40 minutes       0.0.0.0:8089->80/tcp, 0.0.0.0:8092->81/tcp                 nginx
3ab21efbe797        webrecorder_frontend           "sh run.sh"              41 minutes ago      Up 40 minutes       0.0.0.0:8096->8096/tcp                                     frontend
92fa919fac98        webrecorder_app                "/docker-entrypoint.…"   41 minutes ago      Up 41 minutes       8080/tcp                                                   app
2afeeeab4cc1        webrecorder_recorder           "/docker-entrypoint.…"   41 minutes ago      Up 41 minutes       8080/tcp                                                   recorder
73fb7228d1e3        webrecorder_warcserver         "/docker-entrypoint.…"   41 minutes ago      Up 41 minutes       8080/tcp                                                   warcserver
2da0cf306a3f        oldwebtoday/shepherd:1.1.0     "/bin/sh -c 'python …"   41 minutes ago      Up 41 minutes       0.0.0.0:9020->9020/tcp                                     shepherd
b3e5a412e179        webrecorder/dat-share          "/bin/sh -c 'node ru…"   41 minutes ago      Up 41 minutes       3000/tcp, 0.0.0.0:3282->3282/tcp, 0.0.0.0:3282->3282/udp   dat
ae128307cd83        webrecorder_redis              "docker-entrypoint.s…"   41 minutes ago      Up 41 minutes       6379/tcp                                                   redis
65939931e68a        webrecorder/behaviors:latest   "docker-entrypoint.s…"   41 minutes ago      Up 41 minutes       3030/tcp                                                   behaviors
818dc14b512a        catatnight/postfix             "/bin/sh -c '/opt/in…"   41 minutes ago      Up 41 minutes                                                                  mailserver

Thank you!

**Comment by saintanger** [comment]
same issue here. It must be the UI thats not displaying them as manually the urls archived still exist in your case http://192.168.0.223:8089/testuser/default-collection/https://www.google.com

**Comment by saintanger** [comment]
@Feribv btw you can checkout branch autopilot-updates for now - the ui works - i think some of the work they have done recently has sneaked into master by mistake

**Comment by ikreymer** [comment]
Yes, you're right, sorry about that! Thought the fix was on master but not quite -- there's a bug with updating the page list, but everything else works.
Yes, the autopilot-updates branch will work now, but its being actively updated.
We're very close to a release, and will merge everything to master soon! Thanks for your patience.

**Comment by ikreymer** [comment]
It's merged now, should work with `master`.. Let us know if you're still having issues.

**Comment by Feribv** [comment]
Hello,
I've updated from master and Collections are workign as expected!
Thank you for your quick fix!
Have a great day!
