### ISSUE TITLE
clearer call to action for recording from the home page

### ISSUE THREAD

**Issue by mashalifshin** [webrecorder/webrecorder#75]

**Comment by mashalifshin** [comment]
I spent a bit of time on homepage copy/overall app tagline today, since this is something Hannah expressed she is not comfortable with doing.  Brain dump as follows:

possibilities for our WHY statement
(this is our mission, our "I have a dream" statement, that completes the phrase "we believe".)
------------------------------
- Everything you do online is yours to save, review and share
- No matter how much the web changes tomorrow, you can preserve how you experience it today.  
- The web changes all the time.  Your web archives persist forever.
- The web is always changing.  Preserve exactly what you browsed, when you browsed it, and share it with the world. 

HOW
------------------------------
- With webrecorder, you can preserve exactly what you see when you're browsing, browse it again any time, and share it with everyone. 
- Now you can preserve and share the web exactly as you see it.
- Use webrecorder to create permanent, shareable archives.


(This approach to presenting a product is based on Simon Sinek's work, this TED talk is a summary: https://www.youtube.com/watch?v=sioZd3AxmnE)

**Comment by ikreymer** [comment]
I thought 'clearer call to action' referred to the where the main action element (the recorder bar) appears so that's its more obvious how to begin recording. I think that's the most important part, the tagline can be updated later..
