### ISSUE TITLE
Creating a 'new recording' page

### ISSUE THREAD

**Issue by ikreymer** [webrecorder/webrecorder#76]
A 'new recording' page should have just the recorder bar, without anything in the content (except perhaps a message to record), to clearly indicate that a new recording is being created.

This will avoid confusion with recorded where the recorder bar appears in the home page or on collection page. Related to #75, creating a new recording on the home page.

**Comment by mashalifshin** [comment]
'/anonymous/$new' and '/<user>/<coll>/$new' as the routes, so they don't conflict with actual recording names

you can look in recscontroller.py for examples on how to add a new route, that's probably best place..

in init_routes()

probably you want to get the collection info for the collection title, that is done in collscontroller.py, so i guess it could go there as well..

probably just need to set user, coll, coll_title on the returned dictionary. probably just return a subset of what `get_collection_info_for_view` does for the collection info page
