### ISSUE TITLE
Problems with WARC file exported from Webrecorder

### ISSUE THREAD

**Issue by UKGWA** [webrecorder/webrecorder#768]
Hi,

I just logged an issue on Webrecorder-player (https://github.com/webrecorder/webrecorder-player/issues/87) but I think it might be more to do with Webrecorder now.

Basically, I created a large (3.2GB) WARC file by exporting a collection from my local version of the latest Webrecorder running on Ubuntu.

The WARC exports fine, or so it seems.

Then I try to either:
(a) to play it back in webrecorder player but lots of the content is missing; or
(b) we try to index it into pywb using cdx-indexer (with the -s switch) but end up getting a ‘error -3 while recompressing data: invalid block type' error.

I have tried exporting the collection several times but get the same result each time. Have also tried running it through warcio, too.

Any ideas? I can share the WARC file in question to help.

Thanks,
Tom

**Comment by ikreymer** [comment]
Hi Tom, yes, would you be able to share the WARC in question and can take a further look?
Thanks!

**Comment by UKGWA** [comment]
Thanks Ilya,
I’ve sent you the links by email.
Tom

**Comment by ikreymer** [comment]
Should be fixed in WR Player 1.8.0 release.

**Comment by UKGWA** [comment]
Thanks Ilya,
This seems to have fixed the problem!
