### ISSUE TITLE
Show the page that are part of a collection right in the 'collection info' page

### ISSUE THREAD

**Issue by mashalifshin** [webrecorder/webrecorder#77]
- The pages should be ordered by date in reverse chronological order

Goals: 
- Communicate a sense of the collection -> recording -> pages hierarchy

**Comment by mashalifshin** [comment]
Here's a proposal for how this should function.

![recordings_table](https://cloud.githubusercontent.com/assets/709758/14837039/e723932c-0bc9-11e6-8bdd-ae41b7cf72e6.jpg)

- Actions for each recording are still: Browse, Download, Add to recording, Delete
- Actions for each page: Browse, Patch 
- Default action for clicking on recording name: Expand row to show pages
- Default action for clicking on a page: Browse page

It would work, roughly, like this:
- http://www.jqueryscript.net/demo/DataTables-Jquery-Table-Plugin/examples/api/row_details.html
(Note that in the example above, the "details" content is just in the first column, whereas in our case each page will have content for all the columns (last recorded, size, and actions)

**Comment by ikreymer** [comment]
Yes, I think that makes sense.. (and I think the dropdown was in one of the earlier mockups as well). 
Maybe there should be an option to expand all?
Let's try it and see how it feels.

-
