### ISSUE TITLE
Port 80 Configuration

### ISSUE THREAD

**Issue by qome** [webrecorder/webrecorder#778]
I just completed a new installation of Webrecorder using the Docker method on Debian 10.2. When I click "Start Capture" I get no feedback from the web interface and no logs in any of the Docker applications. I do get errors in my browser console about my browser trying to access port 80 of my instance and I don't know why it's trying to access anything there.

![image](https://user-images.githubusercontent.com/58382620/72669802-c1d8b200-39fb-11ea-8018-a1d6b42e18e5.png)

![image](https://user-images.githubusercontent.com/58382620/72669809-d7e67280-39fb-11ea-9a15-d51190c171c0.png)

When clicking on my username
![image](https://user-images.githubusercontent.com/58382620/72669819-111ee280-39fc-11ea-8b36-66b83470e50e.png)

This is a fresh VM with nothing else configured on it except Docker Engine, Docker Compose, and Webrecorder. The only modification I have made to Webrecorder is to change the two _HOST values, run ./recreate.sh, run ./install-browsers.sh, and run ./recreate.sh again.

**Comment by dwaaan** [comment]
I just had the same problem, the fix was setting the ports in wr.env:
APP_HOST - port 8089
CONTENT_HOST - port 8092

**Comment by qome** [comment]
Thanks.
