### ISSUE TITLE
clicking on tweet records JSON file

### ISSUE THREAD

**Issue by hannahlwang** [webrecorder/webrecorder#78]
to recreate:
- enter https://twitter.com/webrecorder_io into the webrecorder URL bar and click record
- click first tweet (while in record mode)
- click "Replay" --> JSON file, rather than tweet page (https://webrecorder.io/hannahlwang/testing2/https://twitter.com/webrecorder_io/status/720900625295405057)

this issue does not occur when the tweet link is entered directly into the URL bar (https://webrecorder.io/hannahlwang/testing2/20160427172112/https://twitter.com/webrecorder_io/status/720900625295405057)

**Comment by ikreymer** [comment]
Thanks for the report and the detailed repro steps! Unfortunately, this is a hard problem as twitter serves different content when loading a tweet from an existing page vs directly. Will update this with more thoughts on this issiue.
