### ISSUE TITLE
It doesn't work properly with Pale Moon

### ISSUE THREAD

**Issue by Zero3K** [webrecorder/webrecorder#782]
The url in the address bar it displays doesn't change when I go to a different page. Please fix it.

**Comment by kbhasi** [comment]
Ah, a fellow Pale Moon user! Right, I've also noticed it doesn't track pages the last time I used it, so I have to use one of their "cloud" Web browsers, or Firefox ESR which I also have _(I use Debian which uses that instead of regular Firefox)_.

**Comment by m4rk3r** [comment]
Please file a bug report via the header button on webrecorder.io - we use those reports to address content errors
