### ISSUE TITLE
ulimit not found

### ISSUE THREAD

**Issue by dGilli** [webrecorder/webrecorder#789]
The `app`, `recorder` and `warcserver` services all throw the same `ulimit: not found` from their docker-compose command.

Am I missing a build step? I can't seem to find a reference to it anywhere in the webrecorder dir either.

**Comment by m4rk3r** [comment]
hi @dGilli, some setups require the `ulimit` config.. you can remove it from the `docker-compose.yml` to get around the `ulimit: not found` error

**Comment by sbaechler** [comment]
Could you not just make sure that ulimit is available in the base image?
