### ISSUE TITLE
"doesn't look right" improvements

### ISSUE THREAD

**Issue by ikreymer** [webrecorder/webrecorder#8]
The "Doesn't Look Right" Error Report just goes into a redis list for now.
Should make it automatically email support@webrecorder.io and include email of user, if any, so that we can respond to the error report directly to the user.

**Comment by mashalifshin** [comment]
also provide feedback to the user that their feedback has been received

(i put a feedback on ur feedback so you can feedback while u feedback.  is that meme still relevant? ;-)
