### ISSUE TITLE
Clarify that recording has stopped when someone navigates away from the recorder

### ISSUE THREAD

**Issue by mashalifshin** [webrecorder/webrecorder#80]

**Comment by mashalifshin** [comment]
a standard dismissible flash message, that appears on the whatever the next view is after recording stopped, styled as info, saying something like "You have navigated away from the recorder.  Don't worry, we automatically stopped recording for you"

**Comment by mashalifshin** [comment]
check referer.. if you navigate to any info page or home page from a recording page, could activate the flash message

**Comment by ikreymer** [comment]
I dunno... this seems like too much messaging.. The temporary collection description could includes this type of message, along with the other stuff. Logged-in users presumably already know this, and it may be annoying to see this every time.

**Comment by ikreymer** [comment]
Recording state has been made more obvious visually as well as collection page info. Closing for now.
