### ISSUE TITLE
Question: log4j somewhere used in conifer?

### ISSUE THREAD

**Issue by steph-nb** [webrecorder/webrecorder#839]
Hi,

just to be absolutely sure:
Is log4j used somewhere in conifer?
And is conifer save regarding the latest log4j vulnerability?

Many thanks and BR,
Stephan

**Comment by m4rk3r** [comment]
Our search service is impacted and currently disabled until patched, we'll post updates here: https://twitter.com/RhizomeConifer/status/1470431277056544769
