### ISSUE TITLE
Access to a \ \ URL is rewritten into a wrong URL address

### ISSUE THREAD

**Issue by net592** [webrecorder/webrecorder#85]
**correct**: www.tita.com/api/v1/110006/105668813/iTalent/user/view/Channl?name=TelantHome&to_user_id=105668813&callback=jQuery110208182656035665294_1462671111599&_=1462671111600
**Webrecorder processing** :http://54.222.172.0/record/mp_///www.tita.com/105668813/ITalentHome/undefined//www.tita.com/api/v1/110006/105668813/iTalent/user/view/Channl?name=TelantHome&to_user_id=105668813&callback=jQuery110208182656035665294_1462671111599&_=1462671111600

Ask the boss whether can set the rule matching
Thank you for

**Comment by m4rk3r** [comment]
This appears to be fixed, please reopen if you are still encountering this issue. Thanks!
