### ISSUE TITLE
Static Snapshot not working (on instagram profiles)

### ISSUE THREAD

**Issue by despens** [webrecorder/webrecorder#87]
I have put an instagram profile to a state where the browser shows around 1000 images.

When I click the "static snapshot" button then, the icon stays inactive for some time, but no static snapshot is appearing in the records list.

Taking a snapshot has worked recently on the [Veternas and Rucas instagram](http://webenact.rhizome.org/veteranas-and-rucas/20160217193311/http://www.instagram.com/veteranas_and_rucas/) that had more than 1500 images.

Any ideas?

**Comment by ikreymer** [comment]
Fix static snapshots in new version.

**Comment by ikreymer** [comment]
Covered by #88
